### PR TITLE
Update minimum deployment target to iOS 12.0

### PR DESCRIPTION
**Pull request by ag-drivequant**
Due to an issue with Xcode 14.3 and Xcode 15, pod spec lint is failing when dependencies are targeting iOS version. 
This change should fix the issue when a podspec uses `WARangeSlider` as a dependency.

More details about pod spec lint problem at: https://github.com/CocoaPods/CocoaPods/issues/11839

### CODE REVIEW

**Review by warchimede — APPROVED** [review]
Thanks for your contribution :)

Since this repo is pretty old now, I might have to take a look for a more global update, including SPM support maybe.

**Comment by ag-drivequant** [comment]
> Thanks for your contribution :)
> 
> Since this repo is pretty old now, I might have to take a look for a more global update, including SPM support maybe.

Thanks for merging!
Will you publish this podspec update to CocoaPods public repo?

**Comment by warchimede** [comment]
Hi @ag-drivequant,

I'm working on it, it will be available soon 👍🏽

**Comment by warchimede** [comment]
Hello @ag-drivequant 👋🏽 ,

Version 1.2.0 is out ! Let me know if everything is ok :)

**Comment by ag-drivequant** [comment]
> Hello @ag-drivequant 👋🏽 ,
> 
> Version 1.2.0 is out ! Let me know if everything is ok :)

Thank your for the release! It's working perfectly!

**Pull request merged**
